/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,js}'],
  theme: {
    screens: {
      sm: '640px',
      ms: '700px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      print: { raw: 'print' },
    },
    extend: {
      colors: {
        currentColor: 'currentColor',

        primary: 'var(--app-sys-color-primary)',
        'on-primary': 'var(--app-sys-color-on-primary)',
        'primary-container': 'var(--app-sys-color-primary-container)',
        'on-primary-container': 'var(--app-sys-color-on-primary-container)',
        secondary: 'var(--app-sys-color-secondary)',
        'on-secondary': 'var(--app-sys-color-on-secondary)',
        'secondary-container': 'var(--app-sys-color-secondary-container)',
        'on-secondary-container': 'var(--app-sys-color-on-secondary-container)',
        tertiary: 'var(--app-sys-color-tertiary)',
        'on-tertiary': 'var(--app-sys-color-on-tertiary)',
        'tertiary-container': 'var(--app-sys-color-tertiary-container)',
        'on-tertiary-container': 'var(--app-sys-color-on-tertiary-container)',
        error: 'var(--app-sys-color-error)',
        'error-container': 'var(--app-sys-color-error-container)',
        'on-error': 'var(--app-sys-color-on-error)',
        'on-error-container': 'var(--app-sys-color-on-error-container)',
        background: 'var(--app-sys-color-background)',
        'on-background': 'var(--app-sys-color-on-background)',
        surface: 'var(--app-sys-color-surface)',
        'on-surface': 'var(--app-sys-color-on-surface)',
        'surface-variant': 'var(--app-sys-color-surface-variant)',
        'on-surface-variant': 'var(--app-sys-color-on-surface-variant)',
        outline: 'var(--app-sys-color-outline)',
        'inverse-on-surface': 'var(--app-sys-color-inverse-on-surface)',
        'inverse-surface': 'var(--app-sys-color-inverse-surface)',
        'inverse-primary': 'var(--app-sys-color-inverse-primary)',
        shadow: 'var(--app-sys-color-shadow)',
        'surface-tint': 'var(--app-sys-color-surface-tint)',
        'surface-tint-color': 'var(--app-sys-color-surface-tint-color)',
      },
    },
  },
  plugins: [],
};
